#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}")" && pwd )";
sudo rm /usr/local/bin/sv
sudo ln -s $DIR/sv /usr/local/bin/sv
sudo rm /usr/local/bin/ssh.config
sudo ln -s $DIR/ssh.config /usr/local/bin/ssh.config
sudo rm /usr/local/bin/sv_exp
sudo ln -s $DIR/sv_exp /usr/local/bin/sv_exp
